server:
  port: 8090
logging:
  config: config/logback.groovy
spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      username: ${MONGO_USER}
      password: ${MONGO_PASS}